# Generated by Django 3.1.4 on 2020-12-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='link',
            new_name='original_url',
        ),
    ]
