# Generated by Django 3.1.4 on 2020-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_shorturl_result_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='result_url',
            field=models.URLField(),
        ),
    ]
